<?php

define( 'PHARMACARE_CORE_VERSION', '1.1.1' );
define( 'PHARMACARE_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'PHARMACARE_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'PHARMACARE_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'PHARMACARE_CORE_ASSETS_PATH', PHARMACARE_CORE_ABS_PATH . '/assets' );
define( 'PHARMACARE_CORE_ASSETS_URL_PATH', PHARMACARE_CORE_URL_PATH . 'assets' );
define( 'PHARMACARE_CORE_INC_PATH', PHARMACARE_CORE_ABS_PATH . '/inc' );
define( 'PHARMACARE_CORE_INC_URL_PATH', PHARMACARE_CORE_URL_PATH . 'inc' );
define( 'PHARMACARE_CORE_CPT_PATH', PHARMACARE_CORE_INC_PATH . '/post-types' );
define( 'PHARMACARE_CORE_CPT_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/post-types' );
define( 'PHARMACARE_CORE_SHORTCODES_PATH', PHARMACARE_CORE_INC_PATH . '/shortcodes' );
define( 'PHARMACARE_CORE_SHORTCODES_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/shortcodes' );
define( 'PHARMACARE_CORE_PLUGINS_PATH', PHARMACARE_CORE_INC_PATH . '/plugins' );
define( 'PHARMACARE_CORE_PLUGINS_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/plugins' );
define( 'PHARMACARE_CORE_HEADER_LAYOUTS_PATH', PHARMACARE_CORE_INC_PATH . '/header/layouts' );
define( 'PHARMACARE_CORE_HEADER_LAYOUTS_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/header/layouts' );
define( 'PHARMACARE_CORE_HEADER_ASSETS_PATH', PHARMACARE_CORE_INC_PATH . '/header/assets' );
define( 'PHARMACARE_CORE_HEADER_ASSETS_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/header/assets' );
define( 'PHARMACARE_CORE_MOBILE_HEADER_LAYOUTS_PATH', PHARMACARE_CORE_INC_PATH . '/mobile-header/layouts' );
define( 'PHARMACARE_CORE_MOBILE_HEADER_LAYOUTS_URL_PATH', PHARMACARE_CORE_INC_URL_PATH . '/mobile-header/layouts' );

define( 'PHARMACARE_CORE_MENU_NAME', 'pharmacare_core_menu' );
define( 'PHARMACARE_CORE_OPTIONS_NAME', 'pharmacare_core_options' );

define( 'PHARMACARE_CORE_PROFILE_SLUG', 'mikado' );
