<?php

define( 'PHARMACARE_MEMBERSHIP_VERSION', '1.0.1' );
define( 'PHARMACARE_MEMBERSHIP_ABS_PATH', dirname( __FILE__ ) );
define( 'PHARMACARE_MEMBERSHIP_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'PHARMACARE_MEMBERSHIP_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'PHARMACARE_MEMBERSHIP_ASSETS_PATH', PHARMACARE_MEMBERSHIP_ABS_PATH . '/assets' );
define( 'PHARMACARE_MEMBERSHIP_ASSETS_URL_PATH', PHARMACARE_MEMBERSHIP_URL_PATH . 'assets' );
define( 'PHARMACARE_MEMBERSHIP_INC_PATH', PHARMACARE_MEMBERSHIP_ABS_PATH . '/inc' );
define( 'PHARMACARE_MEMBERSHIP_INC_URL_PATH', PHARMACARE_MEMBERSHIP_URL_PATH . 'inc' );
define( 'PHARMACARE_MEMBERSHIP_LOGIN_MODAL_PATH', PHARMACARE_MEMBERSHIP_INC_PATH . '/login-modal' );
define( 'PHARMACARE_MEMBERSHIP_LOGIN_MODAL_URL_PATH', PHARMACARE_MEMBERSHIP_INC_URL_PATH . 'login-modal' );
